/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Burntop API
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  DashboardModelsResponse,
  DashboardOverviewResponse,
  DashboardToolsResponse,
  DashboardTrendsResponse,
  GetTrendsApiV1DashboardTrendsGetParams,
  HTTPValidationError,
} from '../generated.schemas';

import { customInstance } from '.././client';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Get aggregated statistics for the authenticated user's dashboard overview.
 * @summary Get dashboard overview
 */
export type getOverviewApiV1DashboardOverviewGetResponse200 = {
  data: DashboardOverviewResponse;
  status: 200;
};

export type getOverviewApiV1DashboardOverviewGetResponseSuccess =
  getOverviewApiV1DashboardOverviewGetResponse200 & {
    headers: Headers;
  };
export type getOverviewApiV1DashboardOverviewGetResponse =
  getOverviewApiV1DashboardOverviewGetResponseSuccess;

export const getGetOverviewApiV1DashboardOverviewGetUrl = () => {
  return `/api/v1/dashboard/overview`;
};

export const getOverviewApiV1DashboardOverviewGet = async (
  options?: RequestInit
): Promise<getOverviewApiV1DashboardOverviewGetResponse> => {
  return customInstance<getOverviewApiV1DashboardOverviewGetResponse>(
    getGetOverviewApiV1DashboardOverviewGetUrl(),
    {
      ...options,
      method: 'GET',
    }
  );
};

export const getGetOverviewApiV1DashboardOverviewGetQueryKey = () => {
  return [`/api/v1/dashboard/overview`] as const;
};

export const getGetOverviewApiV1DashboardOverviewGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getOverviewApiV1DashboardOverviewGet>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getOverviewApiV1DashboardOverviewGet>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetOverviewApiV1DashboardOverviewGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getOverviewApiV1DashboardOverviewGet>>
  > = ({ signal }) => getOverviewApiV1DashboardOverviewGet({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getOverviewApiV1DashboardOverviewGet>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetOverviewApiV1DashboardOverviewGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOverviewApiV1DashboardOverviewGet>>
>;
export type GetOverviewApiV1DashboardOverviewGetQueryError = unknown;

/**
 * @summary Get dashboard overview
 */

export function useGetOverviewApiV1DashboardOverviewGet<
  TData = Awaited<ReturnType<typeof getOverviewApiV1DashboardOverviewGet>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getOverviewApiV1DashboardOverviewGet>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetOverviewApiV1DashboardOverviewGetQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get daily usage trends for charting over a specified time period.
 * @summary Get dashboard trends
 */
export type getTrendsApiV1DashboardTrendsGetResponse200 = {
  data: DashboardTrendsResponse;
  status: 200;
};

export type getTrendsApiV1DashboardTrendsGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getTrendsApiV1DashboardTrendsGetResponseSuccess =
  getTrendsApiV1DashboardTrendsGetResponse200 & {
    headers: Headers;
  };
export type getTrendsApiV1DashboardTrendsGetResponseError =
  getTrendsApiV1DashboardTrendsGetResponse422 & {
    headers: Headers;
  };

export type getTrendsApiV1DashboardTrendsGetResponse =
  | getTrendsApiV1DashboardTrendsGetResponseSuccess
  | getTrendsApiV1DashboardTrendsGetResponseError;

export const getGetTrendsApiV1DashboardTrendsGetUrl = (
  params?: GetTrendsApiV1DashboardTrendsGetParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/dashboard/trends?${stringifiedParams}`
    : `/api/v1/dashboard/trends`;
};

export const getTrendsApiV1DashboardTrendsGet = async (
  params?: GetTrendsApiV1DashboardTrendsGetParams,
  options?: RequestInit
): Promise<getTrendsApiV1DashboardTrendsGetResponse> => {
  return customInstance<getTrendsApiV1DashboardTrendsGetResponse>(
    getGetTrendsApiV1DashboardTrendsGetUrl(params),
    {
      ...options,
      method: 'GET',
    }
  );
};

export const getGetTrendsApiV1DashboardTrendsGetQueryKey = (
  params?: GetTrendsApiV1DashboardTrendsGetParams
) => {
  return [`/api/v1/dashboard/trends`, ...(params ? [params] : [])] as const;
};

export const getGetTrendsApiV1DashboardTrendsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getTrendsApiV1DashboardTrendsGet>>,
  TError = HTTPValidationError,
>(
  params?: GetTrendsApiV1DashboardTrendsGetParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getTrendsApiV1DashboardTrendsGet>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTrendsApiV1DashboardTrendsGetQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTrendsApiV1DashboardTrendsGet>>> = ({
    signal,
  }) => getTrendsApiV1DashboardTrendsGet(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getTrendsApiV1DashboardTrendsGet>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetTrendsApiV1DashboardTrendsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTrendsApiV1DashboardTrendsGet>>
>;
export type GetTrendsApiV1DashboardTrendsGetQueryError = HTTPValidationError;

/**
 * @summary Get dashboard trends
 */

export function useGetTrendsApiV1DashboardTrendsGet<
  TData = Awaited<ReturnType<typeof getTrendsApiV1DashboardTrendsGet>>,
  TError = HTTPValidationError,
>(
  params?: GetTrendsApiV1DashboardTrendsGetParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getTrendsApiV1DashboardTrendsGet>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetTrendsApiV1DashboardTrendsGetQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get usage breakdown by tool/source for the authenticated user.
 * @summary Get tools breakdown
 */
export type getToolsBreakdownApiV1DashboardToolsGetResponse200 = {
  data: DashboardToolsResponse;
  status: 200;
};

export type getToolsBreakdownApiV1DashboardToolsGetResponseSuccess =
  getToolsBreakdownApiV1DashboardToolsGetResponse200 & {
    headers: Headers;
  };
export type getToolsBreakdownApiV1DashboardToolsGetResponse =
  getToolsBreakdownApiV1DashboardToolsGetResponseSuccess;

export const getGetToolsBreakdownApiV1DashboardToolsGetUrl = () => {
  return `/api/v1/dashboard/tools`;
};

export const getToolsBreakdownApiV1DashboardToolsGet = async (
  options?: RequestInit
): Promise<getToolsBreakdownApiV1DashboardToolsGetResponse> => {
  return customInstance<getToolsBreakdownApiV1DashboardToolsGetResponse>(
    getGetToolsBreakdownApiV1DashboardToolsGetUrl(),
    {
      ...options,
      method: 'GET',
    }
  );
};

export const getGetToolsBreakdownApiV1DashboardToolsGetQueryKey = () => {
  return [`/api/v1/dashboard/tools`] as const;
};

export const getGetToolsBreakdownApiV1DashboardToolsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getToolsBreakdownApiV1DashboardToolsGet>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getToolsBreakdownApiV1DashboardToolsGet>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetToolsBreakdownApiV1DashboardToolsGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getToolsBreakdownApiV1DashboardToolsGet>>
  > = ({ signal }) => getToolsBreakdownApiV1DashboardToolsGet({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getToolsBreakdownApiV1DashboardToolsGet>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetToolsBreakdownApiV1DashboardToolsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getToolsBreakdownApiV1DashboardToolsGet>>
>;
export type GetToolsBreakdownApiV1DashboardToolsGetQueryError = unknown;

/**
 * @summary Get tools breakdown
 */

export function useGetToolsBreakdownApiV1DashboardToolsGet<
  TData = Awaited<ReturnType<typeof getToolsBreakdownApiV1DashboardToolsGet>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getToolsBreakdownApiV1DashboardToolsGet>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetToolsBreakdownApiV1DashboardToolsGetQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get usage breakdown by AI model for the authenticated user.
 * @summary Get models breakdown
 */
export type getModelsBreakdownApiV1DashboardModelsGetResponse200 = {
  data: DashboardModelsResponse;
  status: 200;
};

export type getModelsBreakdownApiV1DashboardModelsGetResponseSuccess =
  getModelsBreakdownApiV1DashboardModelsGetResponse200 & {
    headers: Headers;
  };
export type getModelsBreakdownApiV1DashboardModelsGetResponse =
  getModelsBreakdownApiV1DashboardModelsGetResponseSuccess;

export const getGetModelsBreakdownApiV1DashboardModelsGetUrl = () => {
  return `/api/v1/dashboard/models`;
};

export const getModelsBreakdownApiV1DashboardModelsGet = async (
  options?: RequestInit
): Promise<getModelsBreakdownApiV1DashboardModelsGetResponse> => {
  return customInstance<getModelsBreakdownApiV1DashboardModelsGetResponse>(
    getGetModelsBreakdownApiV1DashboardModelsGetUrl(),
    {
      ...options,
      method: 'GET',
    }
  );
};

export const getGetModelsBreakdownApiV1DashboardModelsGetQueryKey = () => {
  return [`/api/v1/dashboard/models`] as const;
};

export const getGetModelsBreakdownApiV1DashboardModelsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getModelsBreakdownApiV1DashboardModelsGet>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getModelsBreakdownApiV1DashboardModelsGet>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetModelsBreakdownApiV1DashboardModelsGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getModelsBreakdownApiV1DashboardModelsGet>>
  > = ({ signal }) => getModelsBreakdownApiV1DashboardModelsGet({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getModelsBreakdownApiV1DashboardModelsGet>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetModelsBreakdownApiV1DashboardModelsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getModelsBreakdownApiV1DashboardModelsGet>>
>;
export type GetModelsBreakdownApiV1DashboardModelsGetQueryError = unknown;

/**
 * @summary Get models breakdown
 */

export function useGetModelsBreakdownApiV1DashboardModelsGet<
  TData = Awaited<ReturnType<typeof getModelsBreakdownApiV1DashboardModelsGet>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getModelsBreakdownApiV1DashboardModelsGet>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetModelsBreakdownApiV1DashboardModelsGetQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}
