"""add_timestamp_columns_to_referral_clicks

Revision ID: f370682185e5
Revises: 461920f4f18c
Create Date: 2026-01-08 13:05:30.729531+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f370682185e5'
down_revision: str | None = '461920f4f18c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referral_clicks', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('referral_clicks', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('referral_clicks', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_referral_clicks_deleted_at'), 'referral_clicks', ['deleted_at'], unique=False)
    op.alter_column('usage_records', 'synced_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='NOW()',
               existing_nullable=False)
    op.alter_column('user_achievements', 'unlocked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='NOW()',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_achievements', 'unlocked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-01-06 01:52:49.006182+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('usage_records', 'synced_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-01-06 01:52:49.006182+00'::timestamp with time zone"),
               existing_nullable=False)
    op.drop_index(op.f('ix_referral_clicks_deleted_at'), table_name='referral_clicks')
    op.drop_column('referral_clicks', 'deleted_at')
    op.drop_column('referral_clicks', 'updated_at')
    op.drop_column('referral_clicks', 'created_at')
    # ### end Alembic commands ###
