"""simplify_leaderboard_cache

Revision ID: f864422eed1f
Revises: g7h8i9j0k1l2
Create Date: 2026-01-11 00:41:20.511239+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f864422eed1f'
down_revision: str | None = 'g7h8i9j0k1l2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    op.execute("DELETE FROM leaderboard_cache")
    
    op.execute("UPDATE leaderboard_cache SET total_tokens = 0 WHERE total_tokens IS NULL")
    op.alter_column('leaderboard_cache', 'total_tokens',
               existing_type=sa.BIGINT(),
               nullable=False,
               existing_comment='Total tokens used')
    op.drop_index(op.f('ix_leaderboard_cache_leaderboard_type'), table_name='leaderboard_cache')
    op.drop_constraint(op.f('uq_leaderboard_cache_user_type_period'), 'leaderboard_cache', type_='unique')
    op.create_unique_constraint('uq_leaderboard_cache_user_period', 'leaderboard_cache', ['user_id', 'period'])
    op.drop_column('leaderboard_cache', 'diversity_score')
    op.drop_column('leaderboard_cache', 'achievements_unlocked')
    op.drop_column('leaderboard_cache', 'unique_days')
    op.drop_column('leaderboard_cache', 'score')
    op.drop_column('leaderboard_cache', 'cache_efficiency')
    op.drop_column('leaderboard_cache', 'reasoning_tokens')
    op.drop_column('leaderboard_cache', 'leaderboard_type')


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usage_records', 'synced_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-01-09 15:32:22.874649+00'::timestamp with time zone"),
               existing_nullable=False)
    op.add_column('leaderboard_cache', sa.Column('leaderboard_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Type of leaderboard (global, diverse, efficient, streak, rising, reasoning)'))
    op.add_column('leaderboard_cache', sa.Column('reasoning_tokens', sa.BIGINT(), autoincrement=False, nullable=True, comment='Total reasoning tokens used'))
    op.add_column('leaderboard_cache', sa.Column('cache_efficiency', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True, comment='Cache efficiency percentage (0-100)'))
    op.add_column('leaderboard_cache', sa.Column('score', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False, comment='Score used for ranking (type-specific)'))
    op.add_column('leaderboard_cache', sa.Column('unique_days', sa.INTEGER(), autoincrement=False, nullable=True, comment='Number of unique active days'))
    op.add_column('leaderboard_cache', sa.Column('achievements_unlocked', sa.INTEGER(), autoincrement=False, nullable=True, comment='Number of achievements unlocked'))
    op.add_column('leaderboard_cache', sa.Column('diversity_score', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True, comment='Diversity score (unique tools/models)'))
    op.drop_constraint('uq_leaderboard_cache_user_period', 'leaderboard_cache', type_='unique')
    op.create_unique_constraint(op.f('uq_leaderboard_cache_user_type_period'), 'leaderboard_cache', ['user_id', 'leaderboard_type', 'period'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_leaderboard_cache_leaderboard_type'), 'leaderboard_cache', ['leaderboard_type'], unique=False)
    op.alter_column('leaderboard_cache', 'total_tokens',
               existing_type=sa.BIGINT(),
               nullable=True,
               existing_comment='Total tokens used')
    # ### end Alembic commands ###
