/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Burntop API
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  GetFeedApiV1FeedGetParams,
  HTTPValidationError,
  PageActivityResponse,
} from '../generated.schemas';

import { customInstance } from '.././client';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Get activity feed for the authenticated user (activities from users they follow)
 * @summary Get activity feed
 */
export type getFeedApiV1FeedGetResponse200 = {
  data: PageActivityResponse;
  status: 200;
};

export type getFeedApiV1FeedGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getFeedApiV1FeedGetResponseSuccess = getFeedApiV1FeedGetResponse200 & {
  headers: Headers;
};
export type getFeedApiV1FeedGetResponseError = getFeedApiV1FeedGetResponse422 & {
  headers: Headers;
};

export type getFeedApiV1FeedGetResponse =
  | getFeedApiV1FeedGetResponseSuccess
  | getFeedApiV1FeedGetResponseError;

export const getGetFeedApiV1FeedGetUrl = (params?: GetFeedApiV1FeedGetParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/feed?${stringifiedParams}` : `/api/v1/feed`;
};

export const getFeedApiV1FeedGet = async (
  params?: GetFeedApiV1FeedGetParams,
  options?: RequestInit
): Promise<getFeedApiV1FeedGetResponse> => {
  return customInstance<getFeedApiV1FeedGetResponse>(getGetFeedApiV1FeedGetUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getGetFeedApiV1FeedGetQueryKey = (params?: GetFeedApiV1FeedGetParams) => {
  return [`/api/v1/feed`, ...(params ? [params] : [])] as const;
};

export const getGetFeedApiV1FeedGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getFeedApiV1FeedGet>>,
  TError = HTTPValidationError,
>(
  params?: GetFeedApiV1FeedGetParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getFeedApiV1FeedGet>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetFeedApiV1FeedGetQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getFeedApiV1FeedGet>>> = ({ signal }) =>
    getFeedApiV1FeedGet(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getFeedApiV1FeedGet>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetFeedApiV1FeedGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFeedApiV1FeedGet>>
>;
export type GetFeedApiV1FeedGetQueryError = HTTPValidationError;

/**
 * @summary Get activity feed
 */

export function useGetFeedApiV1FeedGet<
  TData = Awaited<ReturnType<typeof getFeedApiV1FeedGet>>,
  TError = HTTPValidationError,
>(
  params?: GetFeedApiV1FeedGetParams,
  options?: {
    query?: UseQueryOptions<Awaited<ReturnType<typeof getFeedApiV1FeedGet>>, TError, TData>;
    request?: SecondParameter<typeof customInstance>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetFeedApiV1FeedGetQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}
