/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Burntop API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  DebugStatsResponse,
  GetLeaderboardApiV1LeaderboardGetParams,
  GetUserLeaderboardRankApiV1LeaderboardUsernameGet200,
  GetUserLeaderboardRankApiV1LeaderboardUsernameGetParams,
  HTTPValidationError,
  LeaderboardResponse,
  RefreshResponse,
} from '../generated.schemas';

import { customInstance } from '.././client';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Get Leaderboard
 */
export type getLeaderboardApiV1LeaderboardGetResponse200 = {
  data: LeaderboardResponse;
  status: 200;
};

export type getLeaderboardApiV1LeaderboardGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getLeaderboardApiV1LeaderboardGetResponseSuccess =
  getLeaderboardApiV1LeaderboardGetResponse200 & {
    headers: Headers;
  };
export type getLeaderboardApiV1LeaderboardGetResponseError =
  getLeaderboardApiV1LeaderboardGetResponse422 & {
    headers: Headers;
  };

export type getLeaderboardApiV1LeaderboardGetResponse =
  | getLeaderboardApiV1LeaderboardGetResponseSuccess
  | getLeaderboardApiV1LeaderboardGetResponseError;

export const getGetLeaderboardApiV1LeaderboardGetUrl = (
  params?: GetLeaderboardApiV1LeaderboardGetParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/leaderboard/?${stringifiedParams}`
    : `/api/v1/leaderboard/`;
};

export const getLeaderboardApiV1LeaderboardGet = async (
  params?: GetLeaderboardApiV1LeaderboardGetParams,
  options?: RequestInit
): Promise<getLeaderboardApiV1LeaderboardGetResponse> => {
  return customInstance<getLeaderboardApiV1LeaderboardGetResponse>(
    getGetLeaderboardApiV1LeaderboardGetUrl(params),
    {
      ...options,
      method: 'GET',
    }
  );
};

export const getGetLeaderboardApiV1LeaderboardGetQueryKey = (
  params?: GetLeaderboardApiV1LeaderboardGetParams
) => {
  return [`/api/v1/leaderboard/`, ...(params ? [params] : [])] as const;
};

export const getGetLeaderboardApiV1LeaderboardGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getLeaderboardApiV1LeaderboardGet>>,
  TError = HTTPValidationError,
>(
  params?: GetLeaderboardApiV1LeaderboardGetParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getLeaderboardApiV1LeaderboardGet>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetLeaderboardApiV1LeaderboardGetQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getLeaderboardApiV1LeaderboardGet>>> = ({
    signal,
  }) => getLeaderboardApiV1LeaderboardGet(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getLeaderboardApiV1LeaderboardGet>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetLeaderboardApiV1LeaderboardGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getLeaderboardApiV1LeaderboardGet>>
>;
export type GetLeaderboardApiV1LeaderboardGetQueryError = HTTPValidationError;

/**
 * @summary Get Leaderboard
 */

export function useGetLeaderboardApiV1LeaderboardGet<
  TData = Awaited<ReturnType<typeof getLeaderboardApiV1LeaderboardGet>>,
  TError = HTTPValidationError,
>(
  params?: GetLeaderboardApiV1LeaderboardGetParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getLeaderboardApiV1LeaderboardGet>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetLeaderboardApiV1LeaderboardGetQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get User Leaderboard Rank
 */
export type getUserLeaderboardRankApiV1LeaderboardUsernameGetResponse200 = {
  data: GetUserLeaderboardRankApiV1LeaderboardUsernameGet200;
  status: 200;
};

export type getUserLeaderboardRankApiV1LeaderboardUsernameGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getUserLeaderboardRankApiV1LeaderboardUsernameGetResponseSuccess =
  getUserLeaderboardRankApiV1LeaderboardUsernameGetResponse200 & {
    headers: Headers;
  };
export type getUserLeaderboardRankApiV1LeaderboardUsernameGetResponseError =
  getUserLeaderboardRankApiV1LeaderboardUsernameGetResponse422 & {
    headers: Headers;
  };

export type getUserLeaderboardRankApiV1LeaderboardUsernameGetResponse =
  | getUserLeaderboardRankApiV1LeaderboardUsernameGetResponseSuccess
  | getUserLeaderboardRankApiV1LeaderboardUsernameGetResponseError;

export const getGetUserLeaderboardRankApiV1LeaderboardUsernameGetUrl = (
  username: string,
  params?: GetUserLeaderboardRankApiV1LeaderboardUsernameGetParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/leaderboard/${username}?${stringifiedParams}`
    : `/api/v1/leaderboard/${username}`;
};

export const getUserLeaderboardRankApiV1LeaderboardUsernameGet = async (
  username: string,
  params?: GetUserLeaderboardRankApiV1LeaderboardUsernameGetParams,
  options?: RequestInit
): Promise<getUserLeaderboardRankApiV1LeaderboardUsernameGetResponse> => {
  return customInstance<getUserLeaderboardRankApiV1LeaderboardUsernameGetResponse>(
    getGetUserLeaderboardRankApiV1LeaderboardUsernameGetUrl(username, params),
    {
      ...options,
      method: 'GET',
    }
  );
};

export const getGetUserLeaderboardRankApiV1LeaderboardUsernameGetQueryKey = (
  username?: string,
  params?: GetUserLeaderboardRankApiV1LeaderboardUsernameGetParams
) => {
  return [`/api/v1/leaderboard/${username}`, ...(params ? [params] : [])] as const;
};

export const getGetUserLeaderboardRankApiV1LeaderboardUsernameGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserLeaderboardRankApiV1LeaderboardUsernameGet>>,
  TError = HTTPValidationError,
>(
  username: string,
  params?: GetUserLeaderboardRankApiV1LeaderboardUsernameGetParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getUserLeaderboardRankApiV1LeaderboardUsernameGet>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetUserLeaderboardRankApiV1LeaderboardUsernameGetQueryKey(username, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getUserLeaderboardRankApiV1LeaderboardUsernameGet>>
  > = ({ signal }) =>
    getUserLeaderboardRankApiV1LeaderboardUsernameGet(username, params, {
      signal,
      ...requestOptions,
    });

  return { queryKey, queryFn, enabled: !!username, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserLeaderboardRankApiV1LeaderboardUsernameGet>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetUserLeaderboardRankApiV1LeaderboardUsernameGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserLeaderboardRankApiV1LeaderboardUsernameGet>>
>;
export type GetUserLeaderboardRankApiV1LeaderboardUsernameGetQueryError = HTTPValidationError;

/**
 * @summary Get User Leaderboard Rank
 */

export function useGetUserLeaderboardRankApiV1LeaderboardUsernameGet<
  TData = Awaited<ReturnType<typeof getUserLeaderboardRankApiV1LeaderboardUsernameGet>>,
  TError = HTTPValidationError,
>(
  username: string,
  params?: GetUserLeaderboardRankApiV1LeaderboardUsernameGetParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getUserLeaderboardRankApiV1LeaderboardUsernameGet>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetUserLeaderboardRankApiV1LeaderboardUsernameGetQueryOptions(
    username,
    params,
    options
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Debug Leaderboard
 */
export type debugLeaderboardApiV1LeaderboardDebugGetResponse200 = {
  data: DebugStatsResponse;
  status: 200;
};

export type debugLeaderboardApiV1LeaderboardDebugGetResponseSuccess =
  debugLeaderboardApiV1LeaderboardDebugGetResponse200 & {
    headers: Headers;
  };
export type debugLeaderboardApiV1LeaderboardDebugGetResponse =
  debugLeaderboardApiV1LeaderboardDebugGetResponseSuccess;

export const getDebugLeaderboardApiV1LeaderboardDebugGetUrl = () => {
  return `/api/v1/leaderboard/debug`;
};

export const debugLeaderboardApiV1LeaderboardDebugGet = async (
  options?: RequestInit
): Promise<debugLeaderboardApiV1LeaderboardDebugGetResponse> => {
  return customInstance<debugLeaderboardApiV1LeaderboardDebugGetResponse>(
    getDebugLeaderboardApiV1LeaderboardDebugGetUrl(),
    {
      ...options,
      method: 'GET',
    }
  );
};

export const getDebugLeaderboardApiV1LeaderboardDebugGetQueryKey = () => {
  return [`/api/v1/leaderboard/debug`] as const;
};

export const getDebugLeaderboardApiV1LeaderboardDebugGetQueryOptions = <
  TData = Awaited<ReturnType<typeof debugLeaderboardApiV1LeaderboardDebugGet>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof debugLeaderboardApiV1LeaderboardDebugGet>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDebugLeaderboardApiV1LeaderboardDebugGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof debugLeaderboardApiV1LeaderboardDebugGet>>
  > = ({ signal }) => debugLeaderboardApiV1LeaderboardDebugGet({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof debugLeaderboardApiV1LeaderboardDebugGet>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type DebugLeaderboardApiV1LeaderboardDebugGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof debugLeaderboardApiV1LeaderboardDebugGet>>
>;
export type DebugLeaderboardApiV1LeaderboardDebugGetQueryError = unknown;

/**
 * @summary Debug Leaderboard
 */

export function useDebugLeaderboardApiV1LeaderboardDebugGet<
  TData = Awaited<ReturnType<typeof debugLeaderboardApiV1LeaderboardDebugGet>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof debugLeaderboardApiV1LeaderboardDebugGet>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getDebugLeaderboardApiV1LeaderboardDebugGetQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Refresh Leaderboard
 */
export type refreshLeaderboardApiV1LeaderboardRefreshPostResponse200 = {
  data: RefreshResponse;
  status: 200;
};

export type refreshLeaderboardApiV1LeaderboardRefreshPostResponseSuccess =
  refreshLeaderboardApiV1LeaderboardRefreshPostResponse200 & {
    headers: Headers;
  };
export type refreshLeaderboardApiV1LeaderboardRefreshPostResponse =
  refreshLeaderboardApiV1LeaderboardRefreshPostResponseSuccess;

export const getRefreshLeaderboardApiV1LeaderboardRefreshPostUrl = () => {
  return `/api/v1/leaderboard/refresh`;
};

export const refreshLeaderboardApiV1LeaderboardRefreshPost = async (
  options?: RequestInit
): Promise<refreshLeaderboardApiV1LeaderboardRefreshPostResponse> => {
  return customInstance<refreshLeaderboardApiV1LeaderboardRefreshPostResponse>(
    getRefreshLeaderboardApiV1LeaderboardRefreshPostUrl(),
    {
      ...options,
      method: 'POST',
    }
  );
};

export const getRefreshLeaderboardApiV1LeaderboardRefreshPostMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof refreshLeaderboardApiV1LeaderboardRefreshPost>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof refreshLeaderboardApiV1LeaderboardRefreshPost>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['refreshLeaderboardApiV1LeaderboardRefreshPost'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof refreshLeaderboardApiV1LeaderboardRefreshPost>>,
    void
  > = () => {
    return refreshLeaderboardApiV1LeaderboardRefreshPost(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RefreshLeaderboardApiV1LeaderboardRefreshPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof refreshLeaderboardApiV1LeaderboardRefreshPost>>
>;

export type RefreshLeaderboardApiV1LeaderboardRefreshPostMutationError = unknown;

/**
 * @summary Refresh Leaderboard
 */
export const useRefreshLeaderboardApiV1LeaderboardRefreshPost = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof refreshLeaderboardApiV1LeaderboardRefreshPost>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof refreshLeaderboardApiV1LeaderboardRefreshPost>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getRefreshLeaderboardApiV1LeaderboardRefreshPostMutationOptions(options);

  return useMutation(mutationOptions);
};
