/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Burntop API
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { HealthResponse } from '../generated.schemas';

import { customInstance } from '.././client';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Check service health for uptime monitoring. Returns 200 OK if all checks pass, 503 Service Unavailable otherwise.
 * @summary Health check endpoint
 */
export type healthCheckApiV1HealthGetResponse200 = {
  data: HealthResponse;
  status: 200;
};

export type healthCheckApiV1HealthGetResponseSuccess = healthCheckApiV1HealthGetResponse200 & {
  headers: Headers;
};
export type healthCheckApiV1HealthGetResponse = healthCheckApiV1HealthGetResponseSuccess;

export const getHealthCheckApiV1HealthGetUrl = () => {
  return `/api/v1/health`;
};

export const healthCheckApiV1HealthGet = async (
  options?: RequestInit
): Promise<healthCheckApiV1HealthGetResponse> => {
  return customInstance<healthCheckApiV1HealthGetResponse>(getHealthCheckApiV1HealthGetUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getHealthCheckApiV1HealthGetQueryKey = () => {
  return [`/api/v1/health`] as const;
};

export const getHealthCheckApiV1HealthGetQueryOptions = <
  TData = Awaited<ReturnType<typeof healthCheckApiV1HealthGet>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof healthCheckApiV1HealthGet>>, TError, TData>;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthCheckApiV1HealthGetQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheckApiV1HealthGet>>> = ({
    signal,
  }) => healthCheckApiV1HealthGet({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthCheckApiV1HealthGet>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthCheckApiV1HealthGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthCheckApiV1HealthGet>>
>;
export type HealthCheckApiV1HealthGetQueryError = unknown;

/**
 * @summary Health check endpoint
 */

export function useHealthCheckApiV1HealthGet<
  TData = Awaited<ReturnType<typeof healthCheckApiV1HealthGet>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof healthCheckApiV1HealthGet>>, TError, TData>;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHealthCheckApiV1HealthGetQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}
