/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Burntop API
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { PlatformStatsResponse } from '../generated.schemas';

import { customInstance } from '.././client';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Public endpoint returning aggregate platform metrics for landing page display.
 * @summary Get platform statistics
 */
export type getPlatformStatsApiV1StatsPlatformGetResponse200 = {
  data: PlatformStatsResponse;
  status: 200;
};

export type getPlatformStatsApiV1StatsPlatformGetResponseSuccess =
  getPlatformStatsApiV1StatsPlatformGetResponse200 & {
    headers: Headers;
  };
export type getPlatformStatsApiV1StatsPlatformGetResponse =
  getPlatformStatsApiV1StatsPlatformGetResponseSuccess;

export const getGetPlatformStatsApiV1StatsPlatformGetUrl = () => {
  return `/api/v1/stats/platform`;
};

export const getPlatformStatsApiV1StatsPlatformGet = async (
  options?: RequestInit
): Promise<getPlatformStatsApiV1StatsPlatformGetResponse> => {
  return customInstance<getPlatformStatsApiV1StatsPlatformGetResponse>(
    getGetPlatformStatsApiV1StatsPlatformGetUrl(),
    {
      ...options,
      method: 'GET',
    }
  );
};

export const getGetPlatformStatsApiV1StatsPlatformGetQueryKey = () => {
  return [`/api/v1/stats/platform`] as const;
};

export const getGetPlatformStatsApiV1StatsPlatformGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getPlatformStatsApiV1StatsPlatformGet>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getPlatformStatsApiV1StatsPlatformGet>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPlatformStatsApiV1StatsPlatformGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getPlatformStatsApiV1StatsPlatformGet>>
  > = ({ signal }) => getPlatformStatsApiV1StatsPlatformGet({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPlatformStatsApiV1StatsPlatformGet>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetPlatformStatsApiV1StatsPlatformGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPlatformStatsApiV1StatsPlatformGet>>
>;
export type GetPlatformStatsApiV1StatsPlatformGetQueryError = unknown;

/**
 * @summary Get platform statistics
 */

export function useGetPlatformStatsApiV1StatsPlatformGet<
  TData = Awaited<ReturnType<typeof getPlatformStatsApiV1StatsPlatformGet>>,
  TError = unknown,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getPlatformStatsApiV1StatsPlatformGet>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetPlatformStatsApiV1StatsPlatformGetQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}
