/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WrappedRouteImport } from './routes/wrapped'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as FollowingRouteImport } from './routes/following'
import { Route as FollowersRouteImport } from './routes/followers'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BadgesRouteImport } from './routes/badges'
import { Route as UsernameRouteImport } from './routes/$username'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PUsernameRouteImport } from './routes/p/$username'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as CompareUserAUserBRouteImport } from './routes/compare/$userA.$userB'
import { Route as ApiBadgeDemoRouteImport } from './routes/api/badge/demo'
import { Route as ApiBadgeUsernameRouteImport } from './routes/api/badge/$username'
import { Route as ApiOgWrappedYearRouteImport } from './routes/api/og/wrapped/$year'
import { Route as ApiOgUsernameWeeklyRouteImport } from './routes/api/og/$username.weekly'
import { Route as ApiOgUsernameStatsRouteImport } from './routes/api/og/$username.stats'

const WrappedRoute = WrappedRouteImport.update({
  id: '/wrapped',
  path: '/wrapped',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowingRoute = FollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowersRoute = FollowersRouteImport.update({
  id: '/followers',
  path: '/followers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgesRoute = BadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameRoute = UsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PUsernameRoute = PUsernameRouteImport.update({
  id: '/p/$username',
  path: '/p/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareUserAUserBRoute = CompareUserAUserBRouteImport.update({
  id: '/compare/$userA/$userB',
  path: '/compare/$userA/$userB',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBadgeDemoRoute = ApiBadgeDemoRouteImport.update({
  id: '/api/badge/demo',
  path: '/api/badge/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBadgeUsernameRoute = ApiBadgeUsernameRouteImport.update({
  id: '/api/badge/$username',
  path: '/api/badge/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgWrappedYearRoute = ApiOgWrappedYearRouteImport.update({
  id: '/api/og/wrapped/$year',
  path: '/api/og/wrapped/$year',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgUsernameWeeklyRoute = ApiOgUsernameWeeklyRouteImport.update({
  id: '/api/og/$username/weekly',
  path: '/api/og/$username/weekly',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgUsernameStatsRoute = ApiOgUsernameStatsRouteImport.update({
  id: '/api/og/$username/stats',
  path: '/api/og/$username/stats',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/badges': typeof BadgesRoute
  '/dashboard': typeof DashboardRoute
  '/followers': typeof FollowersRoute
  '/following': typeof FollowingRoute
  '/friends': typeof FriendsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wrapped': typeof WrappedRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/p/$username': typeof PUsernameRoute
  '/api/badge/$username': typeof ApiBadgeUsernameRoute
  '/api/badge/demo': typeof ApiBadgeDemoRoute
  '/compare/$userA/$userB': typeof CompareUserAUserBRoute
  '/api/og/$username/stats': typeof ApiOgUsernameStatsRoute
  '/api/og/$username/weekly': typeof ApiOgUsernameWeeklyRoute
  '/api/og/wrapped/$year': typeof ApiOgWrappedYearRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/badges': typeof BadgesRoute
  '/dashboard': typeof DashboardRoute
  '/followers': typeof FollowersRoute
  '/following': typeof FollowingRoute
  '/friends': typeof FriendsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wrapped': typeof WrappedRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/p/$username': typeof PUsernameRoute
  '/api/badge/$username': typeof ApiBadgeUsernameRoute
  '/api/badge/demo': typeof ApiBadgeDemoRoute
  '/compare/$userA/$userB': typeof CompareUserAUserBRoute
  '/api/og/$username/stats': typeof ApiOgUsernameStatsRoute
  '/api/og/$username/weekly': typeof ApiOgUsernameWeeklyRoute
  '/api/og/wrapped/$year': typeof ApiOgWrappedYearRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/badges': typeof BadgesRoute
  '/dashboard': typeof DashboardRoute
  '/followers': typeof FollowersRoute
  '/following': typeof FollowingRoute
  '/friends': typeof FriendsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wrapped': typeof WrappedRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/p/$username': typeof PUsernameRoute
  '/api/badge/$username': typeof ApiBadgeUsernameRoute
  '/api/badge/demo': typeof ApiBadgeDemoRoute
  '/compare/$userA/$userB': typeof CompareUserAUserBRoute
  '/api/og/$username/stats': typeof ApiOgUsernameStatsRoute
  '/api/og/$username/weekly': typeof ApiOgUsernameWeeklyRoute
  '/api/og/wrapped/$year': typeof ApiOgWrappedYearRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$username'
    | '/badges'
    | '/dashboard'
    | '/followers'
    | '/following'
    | '/friends'
    | '/leaderboard'
    | '/login'
    | '/profile'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/wrapped'
    | '/auth/callback'
    | '/p/$username'
    | '/api/badge/$username'
    | '/api/badge/demo'
    | '/compare/$userA/$userB'
    | '/api/og/$username/stats'
    | '/api/og/$username/weekly'
    | '/api/og/wrapped/$year'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$username'
    | '/badges'
    | '/dashboard'
    | '/followers'
    | '/following'
    | '/friends'
    | '/leaderboard'
    | '/login'
    | '/profile'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/wrapped'
    | '/auth/callback'
    | '/p/$username'
    | '/api/badge/$username'
    | '/api/badge/demo'
    | '/compare/$userA/$userB'
    | '/api/og/$username/stats'
    | '/api/og/$username/weekly'
    | '/api/og/wrapped/$year'
  id:
    | '__root__'
    | '/'
    | '/$username'
    | '/badges'
    | '/dashboard'
    | '/followers'
    | '/following'
    | '/friends'
    | '/leaderboard'
    | '/login'
    | '/profile'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/wrapped'
    | '/auth/callback'
    | '/p/$username'
    | '/api/badge/$username'
    | '/api/badge/demo'
    | '/compare/$userA/$userB'
    | '/api/og/$username/stats'
    | '/api/og/$username/weekly'
    | '/api/og/wrapped/$year'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsernameRoute: typeof UsernameRoute
  BadgesRoute: typeof BadgesRoute
  DashboardRoute: typeof DashboardRoute
  FollowersRoute: typeof FollowersRoute
  FollowingRoute: typeof FollowingRoute
  FriendsRoute: typeof FriendsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WrappedRoute: typeof WrappedRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  PUsernameRoute: typeof PUsernameRoute
  ApiBadgeUsernameRoute: typeof ApiBadgeUsernameRoute
  ApiBadgeDemoRoute: typeof ApiBadgeDemoRoute
  CompareUserAUserBRoute: typeof CompareUserAUserBRoute
  ApiOgUsernameStatsRoute: typeof ApiOgUsernameStatsRoute
  ApiOgUsernameWeeklyRoute: typeof ApiOgUsernameWeeklyRoute
  ApiOgWrappedYearRoute: typeof ApiOgWrappedYearRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wrapped': {
      id: '/wrapped'
      path: '/wrapped'
      fullPath: '/wrapped'
      preLoaderRoute: typeof WrappedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/following': {
      id: '/following'
      path: '/following'
      fullPath: '/following'
      preLoaderRoute: typeof FollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/followers': {
      id: '/followers'
      path: '/followers'
      fullPath: '/followers'
      preLoaderRoute: typeof FollowersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badges': {
      id: '/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof BadgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username': {
      id: '/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof UsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$username': {
      id: '/p/$username'
      path: '/p/$username'
      fullPath: '/p/$username'
      preLoaderRoute: typeof PUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$userA/$userB': {
      id: '/compare/$userA/$userB'
      path: '/compare/$userA/$userB'
      fullPath: '/compare/$userA/$userB'
      preLoaderRoute: typeof CompareUserAUserBRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/badge/demo': {
      id: '/api/badge/demo'
      path: '/api/badge/demo'
      fullPath: '/api/badge/demo'
      preLoaderRoute: typeof ApiBadgeDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/badge/$username': {
      id: '/api/badge/$username'
      path: '/api/badge/$username'
      fullPath: '/api/badge/$username'
      preLoaderRoute: typeof ApiBadgeUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/wrapped/$year': {
      id: '/api/og/wrapped/$year'
      path: '/api/og/wrapped/$year'
      fullPath: '/api/og/wrapped/$year'
      preLoaderRoute: typeof ApiOgWrappedYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/$username/weekly': {
      id: '/api/og/$username/weekly'
      path: '/api/og/$username/weekly'
      fullPath: '/api/og/$username/weekly'
      preLoaderRoute: typeof ApiOgUsernameWeeklyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/$username/stats': {
      id: '/api/og/$username/stats'
      path: '/api/og/$username/stats'
      fullPath: '/api/og/$username/stats'
      preLoaderRoute: typeof ApiOgUsernameStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsernameRoute: UsernameRoute,
  BadgesRoute: BadgesRoute,
  DashboardRoute: DashboardRoute,
  FollowersRoute: FollowersRoute,
  FollowingRoute: FollowingRoute,
  FriendsRoute: FriendsRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WrappedRoute: WrappedRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  PUsernameRoute: PUsernameRoute,
  ApiBadgeUsernameRoute: ApiBadgeUsernameRoute,
  ApiBadgeDemoRoute: ApiBadgeDemoRoute,
  CompareUserAUserBRoute: CompareUserAUserBRoute,
  ApiOgUsernameStatsRoute: ApiOgUsernameStatsRoute,
  ApiOgUsernameWeeklyRoute: ApiOgUsernameWeeklyRoute,
  ApiOgWrappedYearRoute: ApiOgWrappedYearRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
