/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Burntop API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import type { HTTPValidationError, SyncRequest, SyncResponse } from '../generated.schemas';

import { customInstance } from '.././client';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Sync usage records from CLI clients.

    This endpoint accepts usage records aggregated by date, source, and model.
    It performs the following operations:
    1. Deduplicates records (merges records for same date/source/model)
    2. Calculates costs using the pricing engine
    3. Upserts records to database (using unique constraint on user_id, date, source, model, machine_id)
    4. Updates user streak
    5. Returns comprehensive sync response with stats

    The machine_id field enables multi-machine sync - different machines can sync
    data for the same user without overwriting each other's records.

    Rate limiting will be added via middleware in a future task.
 * @summary Sync usage data
 */
export type syncUsageApiV1SyncPostResponse200 = {
  data: SyncResponse;
  status: 200;
};

export type syncUsageApiV1SyncPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type syncUsageApiV1SyncPostResponseSuccess = syncUsageApiV1SyncPostResponse200 & {
  headers: Headers;
};
export type syncUsageApiV1SyncPostResponseError = syncUsageApiV1SyncPostResponse422 & {
  headers: Headers;
};

export type syncUsageApiV1SyncPostResponse =
  | syncUsageApiV1SyncPostResponseSuccess
  | syncUsageApiV1SyncPostResponseError;

export const getSyncUsageApiV1SyncPostUrl = () => {
  return `/api/v1/sync`;
};

export const syncUsageApiV1SyncPost = async (
  syncRequest: SyncRequest,
  options?: RequestInit
): Promise<syncUsageApiV1SyncPostResponse> => {
  return customInstance<syncUsageApiV1SyncPostResponse>(getSyncUsageApiV1SyncPostUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(syncRequest),
  });
};

export const getSyncUsageApiV1SyncPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof syncUsageApiV1SyncPost>>,
    TError,
    { data: SyncRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof syncUsageApiV1SyncPost>>,
  TError,
  { data: SyncRequest },
  TContext
> => {
  const mutationKey = ['syncUsageApiV1SyncPost'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof syncUsageApiV1SyncPost>>,
    { data: SyncRequest }
  > = (props) => {
    const { data } = props ?? {};

    return syncUsageApiV1SyncPost(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SyncUsageApiV1SyncPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof syncUsageApiV1SyncPost>>
>;
export type SyncUsageApiV1SyncPostMutationBody = SyncRequest;
export type SyncUsageApiV1SyncPostMutationError = HTTPValidationError;

/**
 * @summary Sync usage data
 */
export const useSyncUsageApiV1SyncPost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof syncUsageApiV1SyncPost>>,
    TError,
    { data: SyncRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof syncUsageApiV1SyncPost>>,
  TError,
  { data: SyncRequest },
  TContext
> => {
  const mutationOptions = getSyncUsageApiV1SyncPostMutationOptions(options);

  return useMutation(mutationOptions);
};
