/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Burntop API
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  GetUserInsightsApiV1InsightsGetParams,
  HTTPValidationError,
  InsightsResponse,
} from '../generated.schemas';

import { customInstance } from '.././client';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Get user insights comparing stats to community benchmarks.

This endpoint compares the authenticated user's statistics (tokens, cost,
streak, tools usage, cache efficiency) against community averages and
returns percentile rankings.

**Percentile interpretation:**
- 100 = Top performer (best 1%)
- 50 = Median performer
- 0 = Bottom performer

**Requires authentication.**

Args:
    service: Injected BenchmarkService instance
    user_id: Current authenticated user's ID from Bearer token
    period: Time period for comparison (all, month, week)

Returns:
    InsightsResponse with user stats, community benchmarks, and percentile rankings

Raises:
    NotFoundError: If user not found or benchmarks not available
 * @summary Get User Insights
 */
export type getUserInsightsApiV1InsightsGetResponse200 = {
  data: InsightsResponse;
  status: 200;
};

export type getUserInsightsApiV1InsightsGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getUserInsightsApiV1InsightsGetResponseSuccess =
  getUserInsightsApiV1InsightsGetResponse200 & {
    headers: Headers;
  };
export type getUserInsightsApiV1InsightsGetResponseError =
  getUserInsightsApiV1InsightsGetResponse422 & {
    headers: Headers;
  };

export type getUserInsightsApiV1InsightsGetResponse =
  | getUserInsightsApiV1InsightsGetResponseSuccess
  | getUserInsightsApiV1InsightsGetResponseError;

export const getGetUserInsightsApiV1InsightsGetUrl = (
  params?: GetUserInsightsApiV1InsightsGetParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/insights/?${stringifiedParams}`
    : `/api/v1/insights/`;
};

export const getUserInsightsApiV1InsightsGet = async (
  params?: GetUserInsightsApiV1InsightsGetParams,
  options?: RequestInit
): Promise<getUserInsightsApiV1InsightsGetResponse> => {
  return customInstance<getUserInsightsApiV1InsightsGetResponse>(
    getGetUserInsightsApiV1InsightsGetUrl(params),
    {
      ...options,
      method: 'GET',
    }
  );
};

export const getGetUserInsightsApiV1InsightsGetQueryKey = (
  params?: GetUserInsightsApiV1InsightsGetParams
) => {
  return [`/api/v1/insights/`, ...(params ? [params] : [])] as const;
};

export const getGetUserInsightsApiV1InsightsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserInsightsApiV1InsightsGet>>,
  TError = HTTPValidationError,
>(
  params?: GetUserInsightsApiV1InsightsGetParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getUserInsightsApiV1InsightsGet>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUserInsightsApiV1InsightsGetQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserInsightsApiV1InsightsGet>>> = ({
    signal,
  }) => getUserInsightsApiV1InsightsGet(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserInsightsApiV1InsightsGet>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetUserInsightsApiV1InsightsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserInsightsApiV1InsightsGet>>
>;
export type GetUserInsightsApiV1InsightsGetQueryError = HTTPValidationError;

/**
 * @summary Get User Insights
 */

export function useGetUserInsightsApiV1InsightsGet<
  TData = Awaited<ReturnType<typeof getUserInsightsApiV1InsightsGet>>,
  TError = HTTPValidationError,
>(
  params?: GetUserInsightsApiV1InsightsGetParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getUserInsightsApiV1InsightsGet>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customInstance>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetUserInsightsApiV1InsightsGetQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}
